from pathlib import Path
import numpy as np

PROJECT_ROOT = Path(__file__).resolve().parent.parent
DATA_RAW_DIR = PROJECT_ROOT / "data" / "raw"
DATA_PROCESSED_DIR = PROJECT_ROOT / "data" / "processed"
MODELS_DIR = PROJECT_ROOT / "models"

DEFAULT_SCREEN_RESOLUTION = (1920, 1080)

DESK_X_RANGE = (0.01, 0.29)
DESK_Y_RANGE = (0.19, 0.41)
SIM_TIMESTEP = 0.002
CONTROL_TIMESTEP = 0.01
FRAME_SKIP = 5

PAUSE_THRESHOLD_MS = 500
MIN_TRAJECTORY_POINTS = 8
MIN_TRAJECTORY_DISTANCE = 30

CQL_ALPHA = 1.0
BATCH_SIZE = 256
ACTOR_LR = 1e-4
CRITIC_LR = 3e-4
